### ISSUE TITLE
CMakeCatchTemplatePython isn't renamed within Pybind/Pyboost files

### ISSUE THREAD

**Issue by tdowrick** [MattClarkson/CMakeTemplateRenamer#4]
I have been playing round with wrapping & building wheels for Python modules using CMakeCatchTemplate and noticed a bug - after running the Renamer, the Python module name doesn't change.

i.e. in RenamedProject/Code/PythonBoost/renamedprojectLibPython.cpp it still has:
`BOOST_PYTHON_MODULE(CMakeCatchTemplatePython)`
and the same for the PyBind file:
`PYBIND11_MODULE(CMakeCatchTemplatePython, m) {`

**Comment by MattClarkson** [comment]
yeah - I hadn't thought how to do that yet with bash. Any suggestions? or pull requests?
